"""
MarketPulse Streamlit Pages — History Page
Displays all previously generated investment reports from the reports/ directory in Claude styling.
"""

from datetime import datetime
import os
import sys

import streamlit as st

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from ui.theme import apply_claude_theme, render_claude_header, CLAUDE_COLORS
from config.utils import list_saved_reports

st.set_page_config(page_title="MarketPulse — Report History", page_icon="📂", layout="wide")
apply_claude_theme()

render_claude_header(
    title="Report History",
    subtitle="Archive of all autonomous multi-agent investment reports generated by MarketPulse",
    icon="📂"
)

reports = list_saved_reports()

if not reports:
    st.info("No saved reports found yet. Execute an analysis on the main dashboard to generate an investment report.")
else:
    st.markdown(f"<div style='color:{CLAUDE_COLORS['text_secondary']};font-size:0.9rem;margin-bottom:1rem;'>Found <strong>{len(reports)}</strong> archived report(s):</div>", unsafe_allow_html=True)
    for path in reports:
        filename = os.path.basename(path)
        parts = filename.replace("_report.md", "").split("_")
        ticker = parts[0] if parts else "?"
        try:
            ts = datetime.strptime("_".join(parts[1:3]), "%Y%m%d_%H%M%S")
            date_str = ts.strftime("%B %d, %Y at %H:%M UTC")
        except Exception:
            date_str = "Unknown date"

        col1, col2 = st.columns([3, 1])
        with col1:
            st.markdown(f"""
            <div class='claude-card' style='margin-bottom:0.75rem;'>
                <div style='font-size:1.05rem;font-weight:600;color:{CLAUDE_COLORS["terracotta"]};font-family:Lora,serif;'>📄 {ticker} Investment Report</div>
                <div style='color:{CLAUDE_COLORS["text_secondary"]};font-size:0.8rem;margin-top:0.3rem;'>📅 {date_str} &nbsp;·&nbsp; 📁 {filename}</div>
            </div>
            """, unsafe_allow_html=True)
        with col2:
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            st.download_button(
                label="⬇️ Download (.md)",
                data=content,
                file_name=filename,
                mime="text/markdown",
                key=filename,
            )
            if st.button("👁️ View Report", key=f"view_{filename}"):
                with st.expander(f"Report: {filename}", expanded=True):
                    st.markdown(content)
